# Generated by Django 2.0.2 on 2019-01-14 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='order_number',
            new_name='order_by',
        ),
        migrations.AlterField(
            model_name='cscu',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 0, 19, 50, 62552), verbose_name='Время начала выполнения'),
        ),
    ]
