# Generated by Django 2.0.2 on 2019-01-26 22:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190115_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cscu',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 1, 4, 37, 85450), verbose_name='Время начала выполнения'),
        ),
        migrations.AlterField(
            model_name='server',
            name='contour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server', to='main.Contour', verbose_name='Контур'),
        ),
    ]
