# Generated by Django 2.0.2 on 2019-01-27 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190127_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='cscu',
            name='cmd_output',
            field=models.TextField(null=True, verbose_name='Результат выполнения команды'),
        ),
        migrations.AddField(
            model_name='cscu',
            name='success',
            field=models.BooleanField(default=True, verbose_name='Выполнено успешно'),
        ),
        migrations.AlterField(
            model_name='cscu',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 13, 15, 52, 174562), verbose_name='Время начала выполнения'),
        ),
    ]
