# Generated by Django 2.0.2 on 2019-01-27 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190127_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cscu',
            old_name='success',
            new_name='is_success',
        ),
        migrations.AlterField(
            model_name='cscu',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 13, 22, 18, 609472), verbose_name='Время начала выполнения'),
        ),
    ]
