# Generated by Django 2.0.2 on 2019-01-27 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190127_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cscu',
            name='is_success',
            field=models.NullBooleanField(verbose_name='Статус выполнения'),
        ),
        migrations.AlterField(
            model_name='cscu',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 18, 3, 54, 146882), verbose_name='Время начала выполнения'),
        ),
    ]
