# Generated by Django 2.0.2 on 2019-02-09 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190127_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='servercommand',
            name='with_parameters',
            field=models.BooleanField(default=False, help_text='\n                В поле "Команда для выполнения" динамические параметры должны быть оформлены следующим образом:\n                execute command %PARAM_NAME|Название_параметра%,\n                где PARAM_NAME - динамический параметр, который пользователь введёт при выполнении,\n                    Название_параметра - название поля, в которое польхователь введёт параметр.', verbose_name='Возможность передать параметры в команду'),
        ),
        migrations.AlterField(
            model_name='cscu',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 9, 11, 16, 35, 565664), verbose_name='Время начала выполнения'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='item_id',
            field=models.CharField(help_text='По этому параметру происходит активация пунктов меню<br>Если url== */commands/history/, то нужно указать history', max_length=10, verbose_name='Id на странице'),
        ),
        migrations.AlterField(
            model_name='servercommand',
            name='command',
            field=models.TextField(help_text='\n                Введите команду для выполнения на сервере<br>\n                Вы можете ввести custom_command для того, чтобы пользователь сам ввёл команду', max_length=2000, verbose_name='Команда для выполнения'),
        ),
    ]
