# Generated by Django 2.0.2 on 2019-02-19 20:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190219_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cscu',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 19, 23, 56, 57, 82109), verbose_name='Время начала выполнения'),
        ),
        migrations.AlterField(
            model_name='cscu',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_results.TaskResult', to_field='task_id', verbose_name='Задача celery'),
        ),
    ]
