# Generated by Django 2.0.2 on 2019-02-22 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190219_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cscu',
            name='task_id',
        ),
        migrations.AddField(
            model_name='cscu',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Задача celery'),
        ),
        migrations.AlterField(
            model_name='cscu',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 19, 11, 6, 774223), verbose_name='Время начала выполнения'),
        ),
    ]
